apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
  labels:
    app: ledger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
        - name: ledger-service
          image: ledger-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://172.19.0.1:5432/ledger_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "ledger_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "ledger_pass"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
